apiVersion: apps/v1
kind: Deployment
metadata:
  name: handover-ai-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: smart-5g-ai
  template:
    metadata:
      labels:
        app: smart-5g-ai
    spec:
      containers:
      - name: 5g-ai-container
        image: 5g-handover-ai:latest
        imagePullPolicy: IfNotPresent  # <--- Forces K8s to use your local Jenkins build!
        ports:
        - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: handover-ai-service
spec:
  type: LoadBalancer
  ports:
  - port: 8501
    targetPort: 8501
    nodePort: 30001
  selector:
    app: smart-5g-ai
